- name: Install Go packages
  command: go install "{{ item }}"
  with_items:
    - github.com/tomnomnom/anew@latest
    - github.com/tomnomnom/unfurl@latest
    - github.com/tomnomnom/gf@latest
    - github.com/tomnomnom/meg@latest
    - github.com/tomnomnom/gron@latest
    #    - github.com/projectdiscovery/httpx/cmd/httpx@latest
    #    - github.com/projectdiscovery/shufflednscmd/shuffledns@latest
    #    - github.com/projectdiscovery/katana/cmd/katana@latest
    #    - github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
    #    - github.com/d2mondev/puredns/v2@latest
    #    - github.com/ffuf/ffuf@latest
  tags:
    - gotools
