- name: Install zsh
  apt: name=zsh
  tags:
    zsh
- name: Change shell
  shell: chsh -s `which zsh`
- name: Install the zsh
  shell: curl -L https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh 
